// This file is auto-generated by scripts/update-version.mjs
// Do not edit manually - changes will be overwritten at build time.
export const APP_VERSION = '0.21.0';
export const APP_BUILD_TIME = '2026-01-21T19:23:59.143Z';
export const APP_GIT_COMMIT = '45d8fa7';
