// This file is auto-generated by scripts/update-version.mjs
// Do not edit manually - changes will be overwritten at build time.
export const APP_VERSION = '0.27.0';
export const APP_BUILD_TIME = '2026-01-27T14:20:15.318Z';
export const APP_GIT_COMMIT = '34ef628';
