// This file is auto-generated by scripts/update-version.mjs
// Do not edit manually - changes will be overwritten at build time.
export const APP_VERSION = '0.23.1';
export const APP_BUILD_TIME = '2026-01-22T21:00:45.783Z';
export const APP_GIT_COMMIT = 'edbe5a2';
