import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const pkgPath = path.join(repoRoot, 'package.json');
const versionFile = path.join(repoRoot, 'src', 'app', 'version.ts');

function readPackageVersion() {
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    return pkg.version || '0.0.0';
  } catch (e) {
    console.error('Failed to read package.json for version:', e);
    return '0.0.0';
  }
}

function getGitCommitShort() {
  try {
    const res = spawnSync('git', ['rev-parse', '--short', 'HEAD'], { encoding: 'utf8' });
    if (res.status === 0 && res.stdout) {
      return (res.stdout || '').trim();
    }
    return null;
  } catch (e) {
    return null;
  }
}

function buildVersionFile(version, buildTimeIso, commit) {
  const commitLine = commit ? `export const APP_GIT_COMMIT = '${commit}';\n` : '';
  return `// This file is auto-generated by scripts/update-version.mjs
// Do not edit manually - changes will be overwritten at build time.
export const APP_VERSION = '${version}';
export const APP_BUILD_TIME = '${buildTimeIso}';
${commitLine}`;
}

function writeIfChanged(filePath, content) {
  try {
    // Ensure target directory exists
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    if (fs.existsSync(filePath)) {
      const existing = fs.readFileSync(filePath, 'utf8');
      if (existing === content) {
        console.log('Version file up-to-date:', filePath);
        return;
      }
    }
    fs.writeFileSync(filePath, content, 'utf8');
    console.log('Wrote version file:', filePath);
  } catch (e) {
    console.error('Failed to write version file:', e);
    process.exit(1);
  }
}

const version = readPackageVersion();
const buildTime = new Date().toISOString();
const commit = getGitCommitShort();
const content = buildVersionFile(version, buildTime, commit);
writeIfChanged(versionFile, content);
